### ISSUE TITLE
Implement Query API based in HTTP GET Requests

### ISSUE THREAD

**Issue by adrianobrito** [adrianobrito/vaporwave#13]
The current implementation does not considerate any query string parameters in HTTP GET Requests. In order to define a interface to allow the client perform queries, this proposal aims to define a way of do it via query string parameters.

`GET collection?parameter=value`

The following HTTP Request, should return all itens from `collection` endpoint that has `parameter` property equals `value`. 

P.S: It's recommended that you create a new component and not implement this in current `Database` implementations.

**Comment by azharakbar** [comment]
@adrianobrito I will do it ... :) Pls assign it to me ... :)

**Comment by azharakbar** [comment]
@adrianobrito how can i run the server for development purpose ? I tried all the npm scripts .. . :)

**Comment by azharakbar** [comment]
@adrianobrito What Are the steps to run this project in development mode ?

**Comment by adrianobrito** [comment]
Hey @azharakbar,

Firstly, thank you for the help.
To run the server you need run the following sequence of commands:

* `npm install` in project folder to install dependencies (When you run for the first time)
* `npm run execute` to startup the server

After that, you can dispatch HTTP Request against it in http://localhost:8000. You can use curl, Postman or even some browser in order to do it.


Greetings from Brazil. :smile:

**Comment by azharakbar** [comment]
Hi @adrianobrito ,
I tried to do this ... 
I build the project succesfully and the dist/ have been created
But when i run `npm run execute`...this is the error i get

@adrianobrito/vaporwave@0.0.4 execute /home/mpadariyakam/Desktop/vaporwave
babel src/ -d dist/ | node ./dist/index.js

internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1389:5)
    at startupServer (/home/mpadariyakam/Desktop/vaporwave/dist/server.js:74:14)
    at Object.start (/home/mpadariyakam/Desktop/vaporwave/dist/server.js:54:3)
    at /home/mpadariyakam/Desktop/vaporwave/dist/index.js:29:20
    at Object.<anonymous> (/home/mpadariyakam/Desktop/vaporwave/dist/index.js:44:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)

By the way ... Greetings From India ... :D

**Comment by adrianobrito** [comment]
Hey @azharakbar. 

I've added a fix in `master` branch. Could you pull it, and try to execute again.
Thanks, indeed.

**Comment by azharakbar** [comment]
Sure ... :) 
Thanx .. :D

**Comment by azharakbar** [comment]
@adrianobrito 
Hi, so can you give me a clarification on the issue ?? 
Instead of `curl -X GET "http://localhost:8000/api/users/123123"`
It has to be in the form `curl -X GET "http://localhost:8000/api/users?id=123123"`
??

**Comment by adrianobrito** [comment]
@azharakbar 
> Instead of curl -X GET "http://localhost:8000/api/users/123123"
> It has to be in the form curl -X GET "http://localhost:8000/api/users?id=123123"

Yes, but not only `id`, as another properties like `username` for instance.

> curl -X GET "http://localhost:8000/api/users?id=123123"

This particular approach is not the same of `http://localhost:8000/api/users/123123` because it should return a `api/users` sub-collection instead an individual object.

**Comment by azharakbar** [comment]
Oook ... I will look into it ... 
@adrianobrito

**Comment by adrianobrito** [comment]
I've created a branch with Query API working properly. It's just necessary to add some test cases in order to finish this issue. The referred branch is `feature/query_api`.

**Comment by azharakbar** [comment]
@adrianobrito I will work on it .... sorry for the delay .... :)
